export default [
  {
    node_id: 685918,
    node_name: '由霍乱弧菌埃尔托型引起的霍乱6',
    prj_name: '测试项目',
    area: '测试领域',
    std_vocab: '由霍乱弧菌埃尔托型引起的霍乱6',
    syn_vocab: [
      'ElTor霍乱弧菌致霍乱6',
      '霍乱弧菌引起的霍乱6',
      '埃尔托霍乱弧菌所致霍乱6',
      '埃尔托型霍乱6',
      '霍乱,由于O1群霍乱弧菌,埃尔托生物型所致6',
      '埃尔托霍乱弧菌相关性霍乱6',
      'ElTor霍乱弧菌所引起的霍乱6',
      'ElTor霍乱弧菌所致的霍乱6',
      '埃尔托生物型霍乱6',
      '由霍乱弧菌引起的霍乱6',
      '霍乱弧菌引起霍乱6',
      'ElTor霍乱弧菌所导致的霍乱6',
      '霍乱,由于01群霍乱弧菌,埃尔托生物型所致6',
    ],
    graph: {
      nodes: [
        {
          id: 685918,
          labels: ['标准词'],
          name: '由霍乱弧菌埃尔托型引起的霍乱6',
          properties: { class: '标准词' },
        },
        {
          id: 370294,
          labels: ['原始词'],
          name: 'ElTor霍乱弧菌致霍乱6',
          properties: {},
        },
        {
          id: 370301,
          labels: ['原始词'],
          name: '霍乱弧菌引起的霍乱6',
          properties: {},
        },
        {
          id: 370295,
          labels: ['原始词'],
          name: '埃尔托霍乱弧菌所致霍乱6',
          properties: {},
        },
        {
          id: 370298,
          labels: ['原始词'],
          name: '埃尔托型霍乱6',
          properties: {},
        },
        {
          id: 370300,
          labels: ['原始词'],
          name: '霍乱,由于O1群霍乱弧菌,埃尔托生物型所致6',
          properties: {},
        },
        {
          id: 370296,
          labels: ['原始词'],
          name: '埃尔托霍乱弧菌相关性霍乱6',
          properties: {},
        },
        {
          id: 506450,
          labels: ['原始词'],
          name: 'ElTor霍乱弧菌所引起的霍乱6',
          properties: {},
        },
        {
          id: 370293,
          labels: ['原始词'],
          name: 'ElTor霍乱弧菌所致的霍乱6',
          properties: {},
        },
        {
          id: 370297,
          labels: ['原始词'],
          name: '埃尔托生物型霍乱6',
          properties: {},
        },
        {
          id: 370303,
          labels: ['原始词'],
          name: '由霍乱弧菌引起的霍乱6',
          properties: {},
        },
        {
          id: 370302,
          labels: ['原始词'],
          name: '霍乱弧菌引起霍乱6',
          properties: {},
        },
        {
          id: 506449,
          labels: ['原始词'],
          name: 'ElTor霍乱弧菌所导致的霍乱6',
          properties: {},
        },
        {
          id: 370299,
          labels: ['原始词'],
          name: '霍乱,由于01群霍乱弧菌,埃尔托生物型所致6',
          properties: {},
        },
      ],
      rels: [
        { name: 'is', source: '370294', target: '685918' },
        { name: 'is', source: '370301', target: '685918' },
        { name: 'is', source: '370295', target: '685918' },
        { name: 'is', source: '370298', target: '685918' },
        { name: 'is', source: '370300', target: '685918' },
        { name: 'is', source: '370296', target: '685918' },
        { name: 'is', source: '506450', target: '685918' },
        { name: 'is', source: '370293', target: '685918' },
        { name: 'is', source: '370297', target: '685918' },
        { name: 'is', source: '370303', target: '685918' },
        { name: 'is', source: '370302', target: '685918' },
        { name: 'is', source: '506449', target: '685918' },
        { name: 'is', source: '370299', target: '685918' },
      ],
    },
  },
  {
    node_id: 685918,
    node_name: '由霍乱弧菌埃尔托型引起的霍乱6',
    prj_name: '测试项目2',
    area: '测试领域2',
    std_vocab: '由霍乱弧菌埃尔托型引起的霍乱6',
    syn_vocab: [
      'ElTor霍乱弧菌致霍乱6',
      '霍乱弧菌引起的霍乱6',
      '埃尔托霍乱弧菌所致霍乱6',
      '埃尔托型霍乱6',
      '霍乱,由于O1群霍乱弧菌,埃尔托生物型所致6',
      '埃尔托霍乱弧菌相关性霍乱6',
      'ElTor霍乱弧菌所引起的霍乱6',
      'ElTor霍乱弧菌所致的霍乱6',
      '埃尔托生物型霍乱6',
      '由霍乱弧菌引起的霍乱6',
      '霍乱弧菌引起霍乱6',
      'ElTor霍乱弧菌所导致的霍乱6',
      '霍乱,由于01群霍乱弧菌,埃尔托生物型所致6',
    ],
    graph: {
      nodes: [
        {
          id: 685918,
          labels: ['标准词'],
          name: '由霍乱弧菌埃尔托型引起的霍乱6',
          properties: { class: '标准词' },
        },
        {
          id: 370294,
          labels: ['原始词'],
          name: 'ElTor霍乱弧菌致霍乱6',
          properties: {},
        },
        {
          id: 370301,
          labels: ['原始词'],
          name: '霍乱弧菌引起的霍乱6',
          properties: {},
        },
        {
          id: 370295,
          labels: ['原始词'],
          name: '埃尔托霍乱弧菌所致霍乱6',
          properties: {},
        },
        {
          id: 370298,
          labels: ['原始词'],
          name: '埃尔托型霍乱6',
          properties: {},
        },
        {
          id: 370300,
          labels: ['原始词'],
          name: '霍乱,由于O1群霍乱弧菌,埃尔托生物型所致6',
          properties: {},
        },
        {
          id: 370296,
          labels: ['原始词'],
          name: '埃尔托霍乱弧菌相关性霍乱6',
          properties: {},
        },
        {
          id: 506450,
          labels: ['原始词'],
          name: 'ElTor霍乱弧菌所引起的霍乱6',
          properties: {},
        },
        {
          id: 370293,
          labels: ['原始词'],
          name: 'ElTor霍乱弧菌所致的霍乱6',
          properties: {},
        },
        {
          id: 370297,
          labels: ['原始词'],
          name: '埃尔托生物型霍乱6',
          properties: {},
        },
        {
          id: 370303,
          labels: ['原始词'],
          name: '由霍乱弧菌引起的霍乱6',
          properties: {},
        },
        {
          id: 370302,
          labels: ['原始词'],
          name: '霍乱弧菌引起霍乱6',
          properties: {},
        },
        {
          id: 506449,
          labels: ['原始词'],
          name: 'ElTor霍乱弧菌所导致的霍乱6',
          properties: {},
        },
        {
          id: 370299,
          labels: ['原始词'],
          name: '霍乱,由于01群霍乱弧菌,埃尔托生物型所致6',
          properties: {},
        },
      ],
      rels: [
        { name: 'is', source: '370294', target: '685918' },
        { name: 'is', source: '370301', target: '685918' },
        { name: 'is', source: '370295', target: '685918' },
        { name: 'is', source: '370298', target: '685918' },
        { name: 'is', source: '370300', target: '685918' },
        { name: 'is', source: '370296', target: '685918' },
        { name: 'is', source: '506450', target: '685918' },
        { name: 'is', source: '370293', target: '685918' },
        { name: 'is', source: '370297', target: '685918' },
        { name: 'is', source: '370303', target: '685918' },
        { name: 'is', source: '370302', target: '685918' },
        { name: 'is', source: '506449', target: '685918' },
        { name: 'is', source: '370299', target: '685918' },
      ],
    },
  },
];
